<?php

namespace Database\Seeders;

use App\Models\Department;
use App\Models\Gender;
use App\Models\Worker;
use App\Models\Religion;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;

class WorkerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->command->info('🏥 Starting WorkerSeeder...');

        // ========== DEBUG: CEK DATA MASTER ==========
        $this->command->info('🔍 Checking master data...');
        $this->command->info('   Genders: ' . Gender::count());
        $this->command->info('   Religions: ' . Religion::count());
        $this->command->info('   Positions: ' . Department::count());

        // ✅ AMBIL DATA (pakai firstOrCreate untuk safety)
        $genderLaki = Gender::firstOrCreate(['name' => 'Laki-laki']);
        $genderPerempuan = Gender::firstOrCreate(['name' => 'Perempuan']);

        $religionIslam = Religion::firstOrCreate(['name' => 'Islam']);
        $religionKristen = Religion::firstOrCreate(['name' => 'Kristen']);
        $religionKatolik = Religion::firstOrCreate(['name' => 'Katolik']);

        $departmentDokter = Department::firstOrCreate(['name' => 'Dokter'], ['description' => 'Dokter umum dan spesialis']);
        $departmentPerawat = Department::firstOrCreate(['name' => 'Perawat'], ['description' => 'Perawat']);
        $departmentBidan = Department::firstOrCreate(['name' => 'Bidan'], ['description' => 'Bidan']);
        $departmentAdmin = Department::firstOrCreate(['name' => 'Admin'], ['description' => 'Staff administrasi']);

        // ✅ VALIDASI FINAL
        if (!$genderLaki || !$religionIslam || !$departmentDokter) {
            $this->command->error('❌ Failed to create/find master data!');
            return;
        }

        $this->command->info('✅ Master data OK');
        $this->command->info('');
        $this->command->info('👥 Creating workers...');

        // ========== DATA WORKERS ==========

        $workers = [
            // ========== MANAGERS (1 per department) ==========
            [
                'name' => 'Dr. Bambang Setiawan, Sp.PD - Manager Dokter',
                'nip' => 'MGR001',
                'email' => 'manager.dokter@rshdi.com',
                'phone_number' => '081234560001',
                'gender_id' => $genderLaki->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentDokter->id,
                'birth_place' => 'Jakarta',
                'birth_date' => '1978-05-15',
                'address' => 'Jl. Sudirman No. 100, Jakarta',
                'hire_date' => '2010-01-01',
                'status' => 'Active',
            ],
            [
                'name' => 'Siti Aminah, S.Kep.Ners - Manager Perawat',
                'nip' => 'MGR002',
                'email' => 'manager.perawat@rshdi.com',
                'phone_number' => '081234560002',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentPerawat->id,
                'birth_place' => 'Bandung',
                'birth_date' => '1980-08-20',
                'address' => 'Jl. Asia Afrika No. 100, Bandung',
                'hire_date' => '2010-06-01',
                'status' => 'Active',
            ],
            [
                'name' => 'Lilis Suryani, S.ST - Manager Bidan',
                'nip' => 'MGR003',
                'email' => 'manager.bidan@rshdi.com',
                'phone_number' => '081234560003',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentBidan->id,
                'birth_place' => 'Surabaya',
                'birth_date' => '1982-03-10',
                'address' => 'Jl. Pemuda No. 100, Surabaya',
                'hire_date' => '2011-01-15',
                'status' => 'Active',
            ],
            [
                'name' => 'Hendra Wijaya, S.E - Manager Admin',
                'nip' => 'MGR004',
                'email' => 'manager.admin@rshdi.com',
                'phone_number' => '081234560004',
                'gender_id' => $genderLaki->id,
                'religion_id' => $religionKristen->id,
                'department_id' => $departmentAdmin->id,
                'birth_place' => 'Medan',
                'birth_date' => '1979-11-25',
                'address' => 'Jl. Gatot Subroto No. 100, Medan',
                'hire_date' => '2010-03-01',
                'status' => 'Active',
            ],

            // ========== HR (1 for all departments) ==========
            [
                'name' => 'Ratna Sari, S.Psi - HR Manager',
                'nip' => 'HR001',
                'email' => 'hr@rshdi.com',
                'phone_number' => '081234560005',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentAdmin->id,
                'birth_place' => 'Jakarta',
                'birth_date' => '1983-07-12',
                'address' => 'Jl. Thamrin No. 88, Jakarta',
                'hire_date' => '2012-01-01',
                'status' => 'Active',
            ],

            // ========== DEPARTEMEN DOKTER (12 pegawai) ==========
            [
                'name' => 'Dr. Ahmad Dahlan, Sp.PD',
                'nip' => 'DKT001',
                'email' => 'ahmad.dahlan@rshdi.com',
                'phone_number' => '081234567801',
                'gender_id' => $genderLaki->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentDokter->id,
                'birth_place' => 'Jakarta',
                'birth_date' => '1985-03-15',
                'address' => 'Jl. Sudirman No. 123, Jakarta',
                'hire_date' => '2015-01-10',
                'status' => 'Active',
            ],
            [
                'name' => 'Dr. Siti Nurhaliza, Sp.A',
                'nip' => 'DKT002',
                'email' => 'siti.nurhaliza@rshdi.com',
                'phone_number' => '081234567802',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentDokter->id,
                'birth_place' => 'Bandung',
                'birth_date' => '1988-07-20',
                'address' => 'Jl. Asia Afrika No. 45, Bandung',
                'hire_date' => '2016-03-15',
                'status' => 'Active',
            ],
            [
                'name' => 'Dr. Budi Santoso, Sp.B',
                'nip' => 'DKT003',
                'email' => 'budi.santoso@rshdi.com',
                'phone_number' => '081234567803',
                'gender_id' => $genderLaki->id,
                'religion_id' => $religionKristen->id,
                'department_id' => $departmentDokter->id,
                'birth_place' => 'Surabaya',
                'birth_date' => '1982-11-08',
                'address' => 'Jl. Pemuda No. 78, Surabaya',
                'hire_date' => '2014-08-20',
                'status' => 'Active',
            ],
            [
                'name' => 'Dr. Rina Marlina, Sp.OG',
                'nip' => 'DKT004',
                'email' => 'rina.marlina@rshdi.com',
                'phone_number' => '081234567804',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentDokter->id,
                'birth_place' => 'Yogyakarta',
                'birth_date' => '1987-09-05',
                'address' => 'Jl. Malioboro No. 23, Yogyakarta',
                'hire_date' => '2016-08-01',
                'status' => 'Active',
            ],
            [
                'name' => 'Dr. Hendra Gunawan, Sp.JP',
                'nip' => 'DKT005',
                'email' => 'hendra.gunawan@rshdi.com',
                'phone_number' => '081234567805',
                'gender_id' => $genderLaki->id,
                'religion_id' => $religionKatolik->id,
                'department_id' => $departmentDokter->id,
                'birth_place' => 'Semarang',
                'birth_date' => '1984-12-18',
                'address' => 'Jl. Pandanaran No. 67, Semarang',
                'hire_date' => '2015-05-20',
                'status' => 'Active',
            ],
            [
                'name' => 'Dr. Maya Indah, Sp.M',
                'nip' => 'DKT006',
                'email' => 'maya.indah@rshdi.com',
                'phone_number' => '081234567806',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentDokter->id,
                'birth_place' => 'Solo',
                'birth_date' => '1990-04-22',
                'address' => 'Jl. Slamet Riyadi No. 45, Solo',
                'hire_date' => '2018-02-15',
                'status' => 'Active',
            ],
            [
                'name' => 'Dr. Fajar Nugroho, Sp.THT',
                'nip' => 'DKT007',
                'email' => 'fajar.nugroho@rshdi.com',
                'phone_number' => '081234567807',
                'gender_id' => $genderLaki->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentDokter->id,
                'birth_place' => 'Malang',
                'birth_date' => '1986-06-30',
                'address' => 'Jl. Ijen No. 89, Malang',
                'hire_date' => '2016-11-01',
                'status' => 'Active',
            ],
            [
                'name' => 'Dr. Dewi Anggraini, Sp.KK',
                'nip' => 'DKT008',
                'email' => 'dewi.anggraini@rshdi.com',
                'phone_number' => '081234567808',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionKristen->id,
                'department_id' => $departmentDokter->id,
                'birth_place' => 'Denpasar',
                'birth_date' => '1989-01-14',
                'address' => 'Jl. Sunset Road No. 12, Denpasar',
                'hire_date' => '2017-07-10',
                'status' => 'Active',
            ],
            [
                'name' => 'Dr. Agus Pratama, Sp.U',
                'nip' => 'DKT009',
                'email' => 'agus.pratama@rshdi.com',
                'phone_number' => '081234567809',
                'gender_id' => $genderLaki->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentDokter->id,
                'birth_place' => 'Palembang',
                'birth_date' => '1983-10-08',
                'address' => 'Jl. Sudirman No. 56, Palembang',
                'hire_date' => '2015-09-15',
                'status' => 'Active',
            ],
            [
                'name' => 'Dr. Linda Kusuma, Sp.An',
                'nip' => 'DKT010',
                'email' => 'linda.kusuma@rshdi.com',
                'phone_number' => '081234567810',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentDokter->id,
                'birth_place' => 'Makassar',
                'birth_date' => '1988-11-25',
                'address' => 'Jl. Perintis Kemerdekaan No. 34, Makassar',
                'hire_date' => '2017-03-20',
                'status' => 'Active',
            ],
            [
                'name' => 'Dr. Rudi Hartono, Sp.S',
                'nip' => 'DKT011',
                'email' => 'rudi.hartono@rshdi.com',
                'phone_number' => '081234567811',
                'gender_id' => $genderLaki->id,
                'religion_id' => $religionKatolik->id,
                'department_id' => $departmentDokter->id,
                'birth_place' => 'Manado',
                'birth_date' => '1985-08-17',
                'address' => 'Jl. Sam Ratulangi No. 78, Manado',
                'hire_date' => '2016-04-10',
                'status' => 'Active',
            ],
            [
                'name' => 'Dr. Wulan Sari, Sp.PK',
                'nip' => 'DKT012',
                'email' => 'wulan.sari@rshdi.com',
                'phone_number' => '081234567812',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentDokter->id,
                'birth_place' => 'Banjarmasin',
                'birth_date' => '1991-02-28',
                'address' => 'Jl. Ahmad Yani No. 90, Banjarmasin',
                'hire_date' => '2018-06-01',
                'status' => 'Active',
            ],

            // ========== DEPARTEMEN PERAWAT (15 pegawai) ==========
            [
                'name' => 'Ani Kusuma, S.Kep',
                'nip' => 'PRW001',
                'email' => 'ani.kusuma@rshdi.com',
                'phone_number' => '081234567821',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentPerawat->id,
                'birth_place' => 'Yogyakarta',
                'birth_date' => '1992-05-12',
                'address' => 'Jl. Malioboro No. 56, Yogyakarta',
                'hire_date' => '2018-02-01',
                'status' => 'Active',
            ],
            [
                'name' => 'Dedi Firmansyah, S.Kep',
                'nip' => 'PRW002',
                'email' => 'dedi.firmansyah@rshdi.com',
                'phone_number' => '081234567822',
                'gender_id' => $genderLaki->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentPerawat->id,
                'birth_place' => 'Medan',
                'birth_date' => '1990-09-25',
                'address' => 'Jl. Gatot Subroto No. 12, Medan',
                'hire_date' => '2017-06-15',
                'status' => 'Active',
            ],
            [
                'name' => 'Rina Wijaya, S.Kep',
                'nip' => 'PRW003',
                'email' => 'rina.wijaya@rshdi.com',
                'phone_number' => '081234567823',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionKristen->id,
                'department_id' => $departmentPerawat->id,
                'birth_place' => 'Semarang',
                'birth_date' => '1994-02-18',
                'address' => 'Jl. Pandanaran No. 89, Semarang',
                'hire_date' => '2019-01-10',
                'status' => 'Active',
            ],
            [
                'name' => 'Bambang Suryanto, S.Kep',
                'nip' => 'PRW004',
                'email' => 'bambang.suryanto@rshdi.com',
                'phone_number' => '081234567824',
                'gender_id' => $genderLaki->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentPerawat->id,
                'birth_place' => 'Jakarta',
                'birth_date' => '1991-07-08',
                'address' => 'Jl. Sudirman No. 234, Jakarta',
                'hire_date' => '2018-03-20',
                'status' => 'Active',
            ],
            [
                'name' => 'Fitri Handayani, S.Kep',
                'nip' => 'PRW005',
                'email' => 'fitri.handayani@rshdi.com',
                'phone_number' => '081234567825',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentPerawat->id,
                'birth_place' => 'Bandung',
                'birth_date' => '1993-11-30',
                'address' => 'Jl. Dago No. 45, Bandung',
                'hire_date' => '2019-05-15',
                'status' => 'Active',
            ],
            [
                'name' => 'Agung Setiawan, S.Kep',
                'nip' => 'PRW006',
                'email' => 'agung.setiawan@rshdi.com',
                'phone_number' => '081234567826',
                'gender_id' => $genderLaki->id,
                'religion_id' => $religionKatolik->id,
                'department_id' => $departmentPerawat->id,
                'birth_place' => 'Surabaya',
                'birth_date' => '1989-04-14',
                'address' => 'Jl. Basuki Rahmat No. 67, Surabaya',
                'hire_date' => '2017-09-01',
                'status' => 'Active',
            ],
            [
                'name' => 'Nur Azizah, S.Kep',
                'nip' => 'PRW007',
                'email' => 'nur.azizah@rshdi.com',
                'phone_number' => '081234567827',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentPerawat->id,
                'birth_place' => 'Solo',
                'birth_date' => '1995-01-22',
                'address' => 'Jl. Slamet Riyadi No. 123, Solo',
                'hire_date' => '2020-02-10',
                'status' => 'Active',
            ],
            [
                'name' => 'Tono Wijaya, S.Kep',
                'nip' => 'PRW008',
                'email' => 'tono.wijaya@rshdi.com',
                'phone_number' => '081234567828',
                'gender_id' => $genderLaki->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentPerawat->id,
                'birth_place' => 'Malang',
                'birth_date' => '1992-06-19',
                'address' => 'Jl. Semeru No. 34, Malang',
                'hire_date' => '2018-07-20',
                'status' => 'Active',
            ],
            [
                'name' => 'Nita Puspita, S.Kep',
                'nip' => 'PRW009',
                'email' => 'nita.puspita@rshdi.com',
                'phone_number' => '081234567829',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionKristen->id,
                'department_id' => $departmentPerawat->id,
                'birth_place' => 'Denpasar',
                'birth_date' => '1994-10-05',
                'address' => 'Jl. Teuku Umar No. 78, Denpasar',
                'hire_date' => '2019-08-15',
                'status' => 'Active',
            ],
            [
                'name' => 'Yanto Prasetyo, S.Kep',
                'nip' => 'PRW010',
                'email' => 'yanto.prasetyo@rshdi.com',
                'phone_number' => '081234567830',
                'gender_id' => $genderLaki->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentPerawat->id,
                'birth_place' => 'Palembang',
                'birth_date' => '1990-12-28',
                'address' => 'Jl. Jendral Sudirman No. 90, Palembang',
                'hire_date' => '2017-11-01',
                'status' => 'Active',
            ],
            [
                'name' => 'Rini Wulandari, S.Kep',
                'nip' => 'PRW011',
                'email' => 'rini.wulandari@rshdi.com',
                'phone_number' => '081234567831',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentPerawat->id,
                'birth_place' => 'Makassar',
                'birth_date' => '1993-03-16',
                'address' => 'Jl. A.P. Pettarani No. 56, Makassar',
                'hire_date' => '2019-04-10',
                'status' => 'Active',
            ],
            [
                'name' => 'Hadi Santoso, S.Kep',
                'nip' => 'PRW012',
                'email' => 'hadi.santoso@rshdi.com',
                'phone_number' => '081234567832',
                'gender_id' => $genderLaki->id,
                'religion_id' => $religionKatolik->id,
                'department_id' => $departmentPerawat->id,
                'birth_place' => 'Manado',
                'birth_date' => '1988-09-09',
                'address' => 'Jl. Pierre Tendean No. 23, Manado',
                'hire_date' => '2016-12-15',
                'status' => 'Active',
            ],
            [
                'name' => 'Sari Indah, S.Kep',
                'nip' => 'PRW013',
                'email' => 'sari.indah@rshdi.com',
                'phone_number' => '081234567833',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentPerawat->id,
                'birth_place' => 'Banjarmasin',
                'birth_date' => '1996-05-21',
                'address' => 'Jl. Lambung Mangkurat No. 45, Banjarmasin',
                'hire_date' => '2020-09-01',
                'status' => 'Active',
            ],
            [
                'name' => 'Eko Prasetyo, S.Kep',
                'nip' => 'PRW014',
                'email' => 'eko.prasetyo@rshdi.com',
                'phone_number' => '081234567834',
                'gender_id' => $genderLaki->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentPerawat->id,
                'birth_place' => 'Pontianak',
                'birth_date' => '1991-08-13',
                'address' => 'Jl. Gajah Mada No. 67, Pontianak',
                'hire_date' => '2018-10-20',
                'status' => 'Active',
            ],
            [
                'name' => 'Lina Marlina, S.Kep',
                'nip' => 'PRW015',
                'email' => 'lina.marlina@rshdi.com',
                'phone_number' => '081234567835',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionKristen->id,
                'department_id' => $departmentPerawat->id,
                'birth_place' => 'Samarinda',
                'birth_date' => '1994-12-07',
                'address' => 'Jl. Pahlawan No. 89, Samarinda',
                'hire_date' => '2019-11-15',
                'status' => 'Active',
            ],

            // ========== DEPARTEMEN BIDAN (12 pegawai) ==========
            [
                'name' => 'Sari Rahmawati, A.Md.Keb',
                'nip' => 'BDN001',
                'email' => 'sari.rahmawati@rshdi.com',
                'phone_number' => '081234567841',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentBidan->id,
                'birth_place' => 'Solo',
                'birth_date' => '1991-04-30',
                'address' => 'Jl. Slamet Riyadi No. 34, Solo',
                'hire_date' => '2017-09-01',
                'status' => 'Active',
            ],
            [
                'name' => 'Dewi Lestari, A.Md.Keb',
                'nip' => 'BDN002',
                'email' => 'dewi.lestari@rshdi.com',
                'phone_number' => '081234567842',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentBidan->id,
                'birth_place' => 'Malang',
                'birth_date' => '1993-08-14',
                'address' => 'Jl. Ijen No. 67, Malang',
                'hire_date' => '2019-03-15',
                'status' => 'Active',
            ],
            [
                'name' => 'Yuli Astuti, A.Md.Keb',
                'nip' => 'BDN003',
                'email' => 'yuli.astuti@rshdi.com',
                'phone_number' => '081234567843',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionKristen->id,
                'department_id' => $departmentBidan->id,
                'birth_place' => 'Jakarta',
                'birth_date' => '1992-06-22',
                'address' => 'Jl. Thamrin No. 123, Jakarta',
                'hire_date' => '2018-05-10',
                'status' => 'Active',
            ],
            [
                'name' => 'Nia Kurniawati, A.Md.Keb',
                'nip' => 'BDN004',
                'email' => 'nia.kurniawati@rshdi.com',
                'phone_number' => '081234567844',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentBidan->id,
                'birth_place' => 'Bandung',
                'birth_date' => '1994-11-18',
                'address' => 'Jl. Braga No. 56, Bandung',
                'hire_date' => '2019-07-20',
                'status' => 'Active',
            ],
            [
                'name' => 'Indah Permata, A.Md.Keb',
                'nip' => 'BDN005',
                'email' => 'indah.permata@rshdi.com',
                'phone_number' => '081234567845',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentBidan->id,
                'birth_place' => 'Surabaya',
                'birth_date' => '1990-02-09',
                'address' => 'Jl. Darmo No. 78, Surabaya',
                'hire_date' => '2017-04-15',
                'status' => 'Active',
            ],
            [
                'name' => 'Ratna Dewi, A.Md.Keb',
                'nip' => 'BDN006',
                'email' => 'ratna.dewi@rshdi.com',
                'phone_number' => '081234567846',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionKatolik->id,
                'department_id' => $departmentBidan->id,
                'birth_place' => 'Yogyakarta',
                'birth_date' => '1993-09-27',
                'address' => 'Jl. Kaliurang No. 90, Yogyakarta',
                'hire_date' => '2018-11-01',
                'status' => 'Active',
            ],
            [
                'name' => 'Wati Susilawati, A.Md.Keb',
                'nip' => 'BDN007',
                'email' => 'wati.susilawati@rshdi.com',
                'phone_number' => '081234567847',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentBidan->id,
                'birth_place' => 'Semarang',
                'birth_date' => '1995-03-15',
                'address' => 'Jl. Pemuda No. 34, Semarang',
                'hire_date' => '2020-01-20',
                'status' => 'Active',
            ],
            [
                'name' => 'Eni Suryani, A.Md.Keb',
                'nip' => 'BDN008',
                'email' => 'eni.suryani@rshdi.com',
                'phone_number' => '081234567848',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentBidan->id,
                'birth_place' => 'Denpasar',
                'birth_date' => '1991-12-11',
                'address' => 'Jl. Hayam Wuruk No. 45, Denpasar',
                'hire_date' => '2017-10-15',
                'status' => 'Active',
            ],
            [
                'name' => 'Nurul Hidayah, A.Md.Keb',
                'nip' => 'BDN009',
                'email' => 'nurul.hidayah@rshdi.com',
                'phone_number' => '081234567849',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentBidan->id,
                'birth_place' => 'Palembang',
                'birth_date' => '1994-07-08',
                'address' => 'Jl. Angkatan 45 No. 67, Palembang',
                'hire_date' => '2019-06-01',
                'status' => 'Active',
            ],
            [
                'name' => 'Tuti Handayani, A.Md.Keb',
                'nip' => 'BDN010',
                'email' => 'tuti.handayani@rshdi.com',
                'phone_number' => '081234567850',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionKristen->id,
                'department_id' => $departmentBidan->id,
                'birth_place' => 'Makassar',
                'birth_date' => '1992-10-25',
                'address' => 'Jl. Veteran No. 23, Makassar',
                'hire_date' => '2018-08-20',
                'status' => 'Active',
            ],
            [
                'name' => 'Fitria Ningsih, A.Md.Keb',
                'nip' => 'BDN011',
                'email' => 'fitria.ningsih@rshdi.com',
                'phone_number' => '081234567851',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentBidan->id,
                'birth_place' => 'Manado',
                'birth_date' => '1996-01-19',
                'address' => 'Jl. Sarapung No. 56, Manado',
                'hire_date' => '2020-03-10',
                'status' => 'Active',
            ],
            [
                'name' => 'Lia Purnama, A.Md.Keb',
                'nip' => 'BDN012',
                'email' => 'lia.purnama@rshdi.com',
                'phone_number' => '081234567852',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentBidan->id,
                'birth_place' => 'Banjarmasin',
                'birth_date' => '1993-05-04',
                'address' => 'Jl. A. Yani No. 78, Banjarmasin',
                'hire_date' => '2019-02-15',
                'status' => 'Active',
            ],

            // ========== DEPARTEMEN ADMIN (10 pegawai) ==========
            [
                'name' => 'Agus Setiawan',
                'nip' => 'ADM001',
                'email' => 'agus.setiawan@rshdi.com',
                'phone_number' => '081234567861',
                'gender_id' => $genderLaki->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentAdmin->id,
                'birth_place' => 'Jakarta',
                'birth_date' => '1995-01-20',
                'address' => 'Jl. Thamrin No. 90, Jakarta',
                'hire_date' => '2020-01-15',
                'status' => 'Active',
            ],
            [
                'name' => 'Maya Sari',
                'nip' => 'ADM002',
                'email' => 'maya.sari@rshdi.com',
                'phone_number' => '081234567862',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionKatolik->id,
                'department_id' => $departmentAdmin->id,
                'birth_place' => 'Surabaya',
                'birth_date' => '1996-06-10',
                'address' => 'Jl. Diponegoro No. 45, Surabaya',
                'hire_date' => '2020-06-01',
                'status' => 'Active',
            ],
            [
                'name' => 'Budi Wijaya',
                'nip' => 'ADM003',
                'email' => 'budi.wijaya@rshdi.com',
                'phone_number' => '081234567863',
                'gender_id' => $genderLaki->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentAdmin->id,
                'birth_place' => 'Bandung',
                'birth_date' => '1994-03-12',
                'address' => 'Jl. Cihampelas No. 67, Bandung',
                'hire_date' => '2019-09-15',
                'status' => 'Active',
            ],
            [
                'name' => 'Siti Nurjanah',
                'nip' => 'ADM004',
                'email' => 'siti.nurjanah@rshdi.com',
                'phone_number' => '081234567864',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentAdmin->id,
                'birth_place' => 'Yogyakarta',
                'birth_date' => '1997-08-28',
                'address' => 'Jl. Kusumanegara No. 89, Yogyakarta',
                'hire_date' => '2021-02-10',
                'status' => 'Active',
            ],
            [
                'name' => 'Rendra Saputra',
                'nip' => 'ADM005',
                'email' => 'rendra.saputra@rshdi.com',
                'phone_number' => '081234567865',
                'gender_id' => $genderLaki->id,
                'religion_id' => $religionKristen->id,
                'department_id' => $departmentAdmin->id,
                'birth_place' => 'Semarang',
                'birth_date' => '1993-11-15',
                'address' => 'Jl. Pahlawan No. 34, Semarang',
                'hire_date' => '2018-12-01',
                'status' => 'Active',
            ],
            [
                'name' => 'Diah Ayu',
                'nip' => 'ADM006',
                'email' => 'diah.ayu@rshdi.com',
                'phone_number' => '081234567866',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentAdmin->id,
                'birth_place' => 'Solo',
                'birth_date' => '1995-04-19',
                'address' => 'Jl. Dr. Radjiman No. 56, Solo',
                'hire_date' => '2020-05-20',
                'status' => 'Active',
            ],
            [
                'name' => 'Hari Prasetyo',
                'nip' => 'ADM007',
                'email' => 'hari.prasetyo@rshdi.com',
                'phone_number' => '081234567867',
                'gender_id' => $genderLaki->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentAdmin->id,
                'birth_place' => 'Malang',
                'birth_date' => '1996-09-07',
                'address' => 'Jl. Veteran No. 78, Malang',
                'hire_date' => '2021-03-15',
                'status' => 'Active',
            ],
            [
                'name' => 'Winda Sari',
                'nip' => 'ADM008',
                'email' => 'winda.sari@rshdi.com',
                'phone_number' => '081234567868',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionKatolik->id,
                'department_id' => $departmentAdmin->id,
                'birth_place' => 'Denpasar',
                'birth_date' => '1994-12-03',
                'address' => 'Jl. Gatot Subroto No. 90, Denpasar',
                'hire_date' => '2019-11-10',
                'status' => 'Active',
            ],
            [
                'name' => 'Joko Susilo',
                'nip' => 'ADM009',
                'email' => 'joko.susilo@rshdi.com',
                'phone_number' => '081234567869',
                'gender_id' => $genderLaki->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentAdmin->id,
                'birth_place' => 'Palembang',
                'birth_date' => '1992-07-24',
                'address' => 'Jl. R. Sukamto No. 45, Palembang',
                'hire_date' => '2018-06-15',
                'status' => 'Active',
            ],
            [
                'name' => 'Ani Wijayanti',
                'nip' => 'ADM010',
                'email' => 'ani.wijayanti@rshdi.com',
                'phone_number' => '081234567870',
                'gender_id' => $genderPerempuan->id,
                'religion_id' => $religionIslam->id,
                'department_id' => $departmentAdmin->id,
                'birth_place' => 'Makassar',
                'birth_date' => '1998-02-16',
                'address' => 'Jl. Cendrawasih No. 23, Makassar',
                'hire_date' => '2021-07-01',
                'status' => 'Active',
            ],
        ];

        // ========== CREATE WORKERS ==========

        foreach ($workers as $workerData) {
            Worker::create($workerData);
            $this->command->info("   ✅ {$workerData['name']}");
        }

        $this->command->info('');
        $this->command->info("📊 Total workers created: " . count($workers));
        $this->command->info("   - Managers: 4");
        $this->command->info("   - HR: 1");
        $this->command->info("   - Dokter: 12");
        $this->command->info("   - Perawat: 15");
        $this->command->info("   - Bidan: 12");
        $this->command->info("   - Admin: 10");
    }
}
