---
id: UC-AD-KelolaHariLibur-Lihat
title: Activity Diagram - Kelola Hari Libur (Lihat)
---
flowchart LR
  start((Mulai)) --> A1

  subgraph Admin
    A1[Pilih menu Hari Libur]
  end

  subgraph Sistem
    S1[Tampilkan halaman Hari Libur]
    S2[Ambil data hari libur dari database]
    S3[Tampilkan daftar hari libur]
  end

  A1 --> S1 --> S2 --> S3 --> endn((Selesai))
