---
id: UC-AD-KelolaRole-Lihat
title: Activity Diagram - Kelola Role (Lihat)
---
flowchart LR
  start((Mulai)) --> A1

  subgraph Admin
    A1[Pilih menu Role]
  end

  subgraph Sistem
    S1[Tampilkan halaman role]
    S2[Ambil daftar role]
    S3[Tampilkan daftar role]
  end

  A1 --> S1 --> S2 --> S3 --> endn((Selesai))
