graph TD
    Start((Start)) --> Aktivitas{Pilih Aktivitas/Proses}

    %% --- PRESENSI MANUAL ---
    Aktivitas -->|Proses Presensi| Datang[Pegawai Datang]
    Datang --> TTD1[Tanda Tangan kertas absensi]
    TTD1 --> Pulang[Pegawai Pulang]
    Pulang --> TTD2[Tanda Tangan kertas absensi]
    TTD2 --> EndPresensi((End))

    %% --- PEMBERKASAN MANUAL ---
    Aktivitas -->|Proses Pemberkasan| PunyaDok[Pegawai Miliki Dokumen]
    PunyaDok --> SerahDok[Serahkan Fotokopi STR/SIP]
    SerahDok --> HRDTerima[HRD Terima Berkas]
    HRDTerima --> Arsip[Arsipkan di Lemari]
    Arsip --> EndBerkas((End))

    %% --- PENGAJUAN MANUAL ---
    Aktivitas -->|Proses Pengajuan Cuti, sakit, izin, tukar shift, dan Perjalanan DInas| IsiForm[Pegawai Isi Form Kertas]
    IsiForm --> Ajukan[Ajukan ke Atasan]
    Ajukan --> CekAtasan{Atasan Setuju?}
    CekAtasan -->|No| Kembali[Kembalikan ke Pegawai]
    Kembali --> EndAjuan((End))
    CekAtasan -->|Yes| TTDFisik[Tanda Tangan Fisik]
    TTDFisik --> SerahTU[Serahkan Form ke TU]
    SerahTU --> TUCatat[TU Catat Secara Manual]
    TUCatat --> EndAjuan

    %% --- REKAPITULASI MANUAL ---
    Aktivitas -->|Proses Rekapitulasi| KumpulTU[TU Kumpulkan Kertas Absensi]
    KumpulTU --> Hitung[Hitung Data per Pegawai]
    Hitung --> BuatLap[Buat Laporan Manual]
    BuatLap --> SerahPimpinan[Serahkan Laporan ke HRD]
    SerahPimpinan --> EndRekap((End))
